Types and variables
MartinsKris/c-sharp pull request #1
Opened 2021-07-15 17:26 UTC by MartinsKris

Types and variables complete tasks.

2021-07-17 09:32 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            b = 2;
Kāpēc noņēmi string, double, float?

2021-07-17 09:33 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            a = "1";
Liec atpakaļ string, Int...

2021-07-17 09:34 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise9/Program.cs
> +                    if (i == 2)
Else if

2021-07-17 09:34 UTC, ausmoons requested changes
Izlabo komentārus

2021-07-17 13:30 UTC, MartinsKris commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            b = 2;
Iznesu viņus ārpus metodēm, jo atšķīrās tikai vērtības katrā no metodēm. Tas sanāk pret uzdevuma noteikumiem, t.i. lieka darbība, ka ir kā kļūda?

2021-07-18 09:22 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            b = 2;
aa, tagad sapratu. ok, var palikt

2021-07-18 09:22 UTC, ausmoons approved these changes

2021-07-19 08:05 UTC, merged