Arithmetic
MartinsKris/c-sharp pull request #2
Opened 2021-07-20 08:48 UTC by MartinsKris

Complete Arithmetics tasks.

2021-07-20 21:07 UTC, ausmoons requested changes

2021-07-20 21:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +                Main(null);
Kkas nav pareizi, ja tev ir 3 vienādo casi

2021-07-20 21:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +            for (int i = 1; i < 111; i++)
i=0,110

2021-07-20 21:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            if (ValueOne == 15 || ValueTwo == 15 || ValueOne + ValueTwo == 15 || ValueOne - ValueTwo == 15 || ValueTwo - ValueOne == 15)
Uzreiz return

2021-07-20 21:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise5/Program.cs
> +                else if (UserNumber > TheRandomNo)
Else

2021-07-20 21:07 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise8/Program.cs
> +        static double EachHours;
Nākamreiz vari deklarēt tādus ar mazo burtu

2021-07-21 06:51 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +            for (int i = 1; i < 111; i++)
Kāpēc jābūt i=0,110, ja ar esošo (i=1) funkcionē?

2021-07-21 07:09 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/Exercise8/Program.cs
> +        static double EachHours;
Ok, skaidrs. Biju pārpratis ka mainīgie, kas ir ārpus metodēm, jāraksta kā PascalCase.

2021-07-21 07:22 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +                Main(null);
Viņi ir katram figūras veidam savi, t.i. katrā ir sava metode laukuma aprēķināšanai. Pēdējā, kopīgā (InputValidation) metode ir ievadīto skaitļu pārbaudei. Vai arī kko ne tā sapratu..?

2021-07-21 07:34 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            if (ValueOne == 15 || ValueTwo == 15 || ValueOne + ValueTwo == 15 || ValueOne - ValueTwo == 15 || ValueTwo - ValueOne == 15)
Ok, izlaboju.

2021-07-21 07:34 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/Exercise5/Program.cs
> +                else if (UserNumber > TheRandomNo)
Ok, izlaboju.

2021-07-21 14:42 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +                Main(null);
Jā, bet tad tev ir jā uzraksta tā, lai nav jāraksta viens un tas pats 3 reizes

2021-07-21 14:42 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +            for (int i = 1; i < 111; i++)
Jo sākas ar 0 un pēdējais cipars ir 110

2021-07-21 14:43 UTC, ausmoons approved these changes

2021-07-21 14:50 UTC, MartinsKris commented on csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +            for (int i = 1; i < 111; i++)
Ā, sapratu.

2021-07-21 18:28 UTC, merged